### ISSUE TITLE
Incompatible with compose 1.5

### ISSUE THREAD

**Issue by robbysmeticapps** [mori-atsushi/katalog#113]
## What happened?
Crash after opening Katalog when using Compose 1.5. Accompanist library had the same issue, here is the PR they did to fix it: https://github.com/google/accompanist/pull/1570

## To Reproduce Steps
Open katalog

## Logs

Crash log:
`java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~XDMluM7VqP9s41a0kH8nFw==/com.randomapp.debug-S1GnuHVnHqiixQHwaE5orw==/base.apk)
                                                                                                    	at jp.co.cyberagent.katalog.compose.navigation.NavRootKt.AnimatedPage(NavRoot.kt:63)
                                                                                                    	at jp.co.cyberagent.katalog.compose.navigation.NavRootKt.NavRoot(NavRoot.kt:24)
                                                                                                    	at jp.co.cyberagent.katalog.compose.page.MainPageKt.MainPage(MainPage.kt:24)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$MainContent$3.invoke(App.kt:83)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$MainContent$3.invoke(App.kt:82)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$ExtRootWrappers$2$1.invoke(App.kt:115)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$ExtRootWrappers$2$1.invoke(App.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at jp.co.cyberagent.katalog.ext.androidtheme.internal.ContextThemeKt.ContextTheme(ContextTheme.kt:21)
                                                                                                    	at jp.co.cyberagent.katalog.ext.androidtheme.internal.AndroidThemeExtKt$createAndroidThemeExt$1.invoke(AndroidThemeExt.kt:13)
                                                                                                    	at jp.co.cyberagent.katalog.ext.androidtheme.internal.AndroidThemeExtKt$createAndroidThemeExt$1.invoke(AndroidThemeExt.kt:12)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$ExtRootWrappers$2.invoke(App.kt:114)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$ExtRootWrappers$2.invoke(App.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt.ExtRootWrappers(App.kt:103)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt.ExtRootWrappers(App.kt:106)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt.MainContent(App.kt:79)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt.access$MainContent(App.kt:1)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$MainContent$katalogValue$1.invoke(Unknown Source:6)
                                                                                                    	at jp.co.cyberagent.katalog.compose.AppKt$MainContent$katalogValue$1.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2443)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2711)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3342)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3320)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3320)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3285)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:772)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
 at 
androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@fb27690, androidx.compose.ui.platform.MotionDurationScaleImpl@27c8b89, StandaloneCoroutine{Cancelling}@681578e, AndroidUiDispatcher@393bbaf]`

**Comment by mori-atsushi** [comment]
Thank you for your report.
I'll fix it.
